name: pangeo
channels:
  - conda-forge
  - intake
  - default
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - gcsfs
  - intake
  - intake-xarray
  - scikit-image
  - scikit-learn
  - dask-ml
  - bokeh
  - holoviews
  - geoviews
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - ipywidgets
  - pip:
    - intake
    - intake-xarray
    - kubernetes
    - git+https://github.com/dask/dask-kubernetes.git
